version: '3.8'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    environment:
      - DB_HOST=mysql
      - DB_NAME=bloodbank
    networks:
      - jenkins-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bloodbank
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/bloodbank.sql:/docker-entrypoint-initdb.d/bloodbank.sql
    networks:
      - jenkins-network

volumes:
  jenkins_home:
  mysql_data:

networks:
  jenkins-network:
